import fs from "node:fs/promises";
import crypto from "node:crypto";
import path from "node:path";
import { ensureDir, pathExists } from "@ai-config-sync/core";

export interface LockPayload {
  pid: number;
  startedAt: string;
  /** Free-form scope label, e.g. "config-repo" or "home-target". */
  scope: string;
  /** Absolute path this lock guards (config repo dir or home). */
  target: string;
  command: string;
  /** Unique ownership token; generated by acquireFileLock. */
  ownerId?: string;
}

// Keep the token for locks acquired by this process. releaseFileLock checks the
// on-disk token before unlinking so an old owner can never remove a lock that
// has since been broken and re-acquired by another process.
const ownedLocks = new Map<string, string>();

export interface AcquireOptions {
  /** Total attempts before giving up (default 50). */
  maxAttempts?: number;
  /** Per-wait base delay ms (default 50). */
  baseDelayMs?: number;
  /** Per-attempt delay step ms (default 30). */
  stepDelayMs?: number;
  /** Stale-lock age in ms before force-breaking (default 30 min). */
  staleMs?: number;
  /** Test hook: throw after acquiring (used to assert release). */
  injectThrowAfterAcquire?: boolean;
}

/**
 * Cross-process filesystem mutex over a single lock file.
 *
 * - acquireLock fails closed (O_EXCL `wx` open) so two processes never share it
 * - stale locks (owner dead or older than staleMs) are broken safely
 * - call within try/finally + releaseLock; never hold across unbounded work
 *
 * Returns the lock file path so the (caller-controlled) finally can release it.
 */
export async function acquireFileLock(
  lockPath: string,
  payload: LockPayload,
  options: AcquireOptions = {},
): Promise<string> {
  const maxAttempts = options.maxAttempts ?? 50;
  const baseDelay = options.baseDelayMs ?? 50;
  const stepDelay = options.stepDelayMs ?? 30;
  const staleMs = options.staleMs ?? 30 * 60 * 1000;

  await ensureDir(path.dirname(lockPath));
  const ownerId = crypto.randomUUID();
  const ownedPayload: LockPayload = { ...payload, ownerId };

  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      const fh = await fs.open(lockPath, "wx");
      try {
        await fh.writeFile(JSON.stringify(ownedPayload, null, 2), "utf8");
      } catch (e) {
        await fh.close().catch(() => {});
        await fs.rm(lockPath, { force: true }).catch(() => {});
        throw e;
      }
      await fh.close();
      if (options.injectThrowAfterAcquire) {
        // Acquired then immediately failed: must not leak the lock file.
        await fs.rm(lockPath, { force: true }).catch(() => {});
        throw new Error("injectThrowAfterAcquire");
      }
      ownedLocks.set(path.resolve(lockPath), ownerId);
      return lockPath;
    } catch (e) {
      const err = e as NodeJS.ErrnoException;
      if (err.code !== "EEXIST") throw e;
      // Stale-lock heuristics
      let stale = false;
      try {
        const raw = await fs.readFile(lockPath, "utf8");
        const existing = JSON.parse(raw) as {
          pid?: number;
          startedAt?: string;
        };
        let ownerAlive: boolean | undefined;
        if (existing.pid) {
          if (existing.pid === process.pid) {
            ownerAlive = true;
          } else {
            try {
              process.kill(existing.pid, 0);
              ownerAlive = true;
            } catch (e) {
              ownerAlive = (e as NodeJS.ErrnoException).code === "EPERM";
            }
          }
        }
        if (existing.startedAt && ownerAlive !== true) {
          const age = Date.now() - Date.parse(existing.startedAt);
          if (Number.isFinite(age) && age > staleMs) stale = true;
        }
        if (ownerAlive === false) stale = true;
        if (stale) {
          await fs.rm(lockPath, { force: true });
          continue;
        }
      } catch (readError) {
        // Another process can observe the O_EXCL-created file before its owner
        // finishes writing JSON. A fresh unreadable file is therefore busy,
        // not corrupt. Only break it after the same stale-age policy applies.
        if ((readError as NodeJS.ErrnoException).code === "ENOENT") continue;
        try {
          const stat = await fs.stat(lockPath);
          if (Date.now() - stat.mtimeMs > staleMs) {
            await fs.rm(lockPath, { force: true });
            continue;
          }
        } catch (statError) {
          if ((statError as NodeJS.ErrnoException).code === "ENOENT") continue;
        }
      }
      await new Promise((r) => setTimeout(r, baseDelay + attempt * stepDelay));
    }
  }
  throw new Error(
    `Lock busy (${payload.scope} on ${payload.target}): ${lockPath}`,
  );
}

export async function releaseFileLock(lockPath: string): Promise<void> {
  const key = path.resolve(lockPath);
  const ownerId = ownedLocks.get(key);
  if (!ownerId) return;
  try {
    const raw = await fs.readFile(lockPath, "utf8");
    const current = JSON.parse(raw) as { ownerId?: string };
    if (current.ownerId === ownerId) {
      await fs.rm(lockPath, { force: true });
    }
  } catch {
    /* ignore — released or already gone */
  } finally {
    // A waiter in this process may acquire the path immediately after our
    // unlink. Do not erase that replacement owner's token from the map.
    if (ownedLocks.get(key) === ownerId) ownedLocks.delete(key);
  }
}

/** Stable lock file path for a given target under a base dir. */
export function lockFilePath(
  baseDir: string,
  scope: string,
  targetPath: string,
): string {
  // Deterministic, filesystem-safe key from the guarded target.
  const key = crypto
    .createHash("sha256")
    .update(path.resolve(targetPath))
    .digest("hex")
    .slice(0, 16);
  return path.join(baseDir, `${scope}-${key}.lock`);
}

/** Run `work` while holding the lock; always release in finally. */
export async function withFileLock<T>(
  lockPath: string,
  payload: LockPayload,
  work: () => Promise<T>,
  options: AcquireOptions = {},
): Promise<T> {
  await acquireFileLock(lockPath, payload, options);
  try {
    return await work();
  } finally {
    await releaseFileLock(lockPath);
  }
}

/** True when a lock file currently exists (diagnostic / tests). */
export async function isLockHeld(lockPath: string): Promise<boolean> {
  return pathExists(lockPath);
}
